CREATE TABLE catalog_courses (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_id INTEGER
        REFERENCES catalog_categories(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    course_code TEXT,
    learning_track_id INTEGER
        REFERENCES catalog_learning_tracks(id) ON DELETE CASCADE NOT NULL,
    certification TEXT NOT NULL,
    description TEXT NOT NULL
);